kernel.config:
  charset:             UTF-8
  error_handler_level: null

web.web: ~

web.templating:
  escaping:       htmlspecialchars
  assets_version: SomeVersionScheme


services:
  ticket.mapper:
    class:  Application\TicketBundle\Model\Ticket\Mapper
  ticket:
    class:  Application\TicketBundle\Service\TicketService
    arguments: [@ticket.mapper]
