imports:
  - { resource: config.yml }

zend.logger:
  priority: debug
  path:     %kernel.logs_dir%/%kernel.environment%.log

web.debug:
  exception: %kernel.debug%
  toolbar:   %kernel.debug%
  ide:       textmate
