kernel.config:
  charset:             UTF-8
  error_handler_level: null

web.web: ~

web.templating:
  escaping:       htmlspecialchars
  assets_version: SomeVersionScheme

web.user:
  class: Application\GuardBundle\SecureUser

ticket.ticket: ~  
ticket.milestone: ~

user.user: ~

mongo.mongo: 
  dbname: springbok
