kernel.config:
  charset:             UTF-8
  error_handler_level: null

web.web: ~

web.templating:
  escaping:       htmlspecialchars
  assets_version: SomeVersionScheme

web.user: ~

springbok.springbok: ~

ticket.ticket: ~  
ticket.milestone: ~

project.project: ~

user.user: ~

mongo.mongo: 
  dbname: springbok
