kernel.config:
  charset:             UTF-8
  error_handler_level: null

web.web: ~

web.templating:
  escaping:       htmlspecialchars
  assets_version: SomeVersionScheme

ticket.ticket: ~  
ticket.milestone: ~

mongo.mongo: 
  dbname: springbok
