user:
  resource: UserBundle/Resources/config/routing.yml

ticket:
  resource: TicketBundle/Resources/config/routing.yml

guard:
  resource: GuardBundle/Resources/config/routing.yml
  
springbok:
  resource: SpringbokBundle/Resources/config/routing.yml

