ticket_read:
  pattern: ticket/:ticket
  defaults: { _bundle: TicketBundle, _controller: Ticket, _action: read }

queue:
  pattern: queue
  defaults: { _bundle: TicketBundle, _controller: Ticket, _action: queue }

milestone_index:
  pattern: /milestones
  defaults: { _bundle: TicketBundle, _controller: Milestone, _action: index }

milestone_read:
  pattern: milestone/:id
  defaults: { _bundle: TicketBundle, _controller: Milestone, _action: read }
