milestone_index:
  pattern: /milestones
  defaults: { _bundle: TicketBundle, _controller: Milestone, _action: index }

tickets_per_milestone:
  pattern: milestone/:milestone/tickets
  defaults: { _bundle: TicketBundle, _controller: Ticket, _action: milestone }
