milestone_index:
  pattern: /milestones
  defaults: { _bundle: TicketBundle, _controller: Milestone, _action: index }

ticket_read:
  pattern: ticket/:ticket
  defaults: { _bundle: TicketBundle, _controller: Ticket, _action: read }


tickets_per_milestone:
  pattern: milestone/:milestone/tickets
  defaults: { _bundle: TicketBundle, _controller: Milestone, _action: milestone }

queue:
  pattern: queue
  defaults: { _bundle: TicketBundle, _controller: Ticket, _action: queue }
