#!/usr/bin/env php
<?php

require_once __DIR__.'/springbokKernel.php';

use Symfony\Framework\WebBundle\Console\Application;

$kernel = new springbokKernel('dev', true);

$application = new Application($kernel);
$application->run();
